url: "https://mkiroshdz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
title: "mkiroshdz" # the name of your site, e.g. ACME Corp.
